In [3]:
import glob
import librosa
import numpy as np


In [7]:
import glob
import librosa
import numpy as np

def extract_feature(file_name):
    
    X, sample_rate = librosa.load(file_name)
    stft = np.abs(librosa.stft(X))
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
    mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X), sr=sample_rate).T,axis=0)
    return mfccs,chroma,mel,contrast,tonnetz

def parse_audio_files(filenames):
    
    rows = len(filenames)
    features, labels, groups = np.zeros((rows,193)), np.zeros((rows)), np.zeros((rows, 1))
    i = 0
    
    for fn in filenames:
        
        try:
            
            mfccs, chroma, mel, contrast,tonnetz = extract_feature(fn)
            ext_features = np.hstack([mfccs,chroma,mel,contrast,tonnetz])
            y_col = int(fn.split('/')[10].split('-')[1])
            group = int(fn.split('/')[10].split('-')[0])
        
        except:
            
            print(fn)
            
        else:
            
            features[i] = ext_features
            labels[i] = y_col
            groups[i] = group
            i += 1
            
    return features, labels, groups




In [8]:
'''
a,b,c,d,e=extract_feature('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold1/7061-6-0-0.wav')
print("mfccs >> ",a,a.shape,"\n\n")
print("chroma >> ",b,b.shape,"\n\n")
print("mel >> ",c,c.shape,"\n\n")
print("contrast >> ",d,d.shape,"\n\n")
print("tonnetz >> ",e,e.shape,"\n\n")
print("np.hstack",np.hstack([a,b,c,d,e]),np.array(np.hstack([a,b,c,d,e])).shape)
'''
f,g,h = parse_audio_files('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold11/11111-10-0-1.wav')
print("feature >> ",f,f.shape,"\n\n")
print("labels >> ",g,g.shape,"\n\n")
print("groups >> ",h,h.shape,"\n\n")

/
h
o
m
e
/
l
i
b
e
d
e
v
/
m
u
t
e
/
m
u
t
e
-
h
e
r
o
/
d
o
w
n
l
o
a
d
/
u
r
b
a
n
s
o
u
n
d
/
U
r
b
a
n
S
o
u
n
d
8
K
/
a
u
d
i
o
/
f
o
l
d
1
1
/
1
1
1
1
1
-
1
0
-
0
-
1
.
w
a
v
feature >>  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (91, 193) 


labels >>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (91,) 


groups >>  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [56]:
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


In [ ]:
audio_files =[]
for i in range(9,10):
    audio_files.extend(glob.glob('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold%d/*.wav'%i))

#print(audio_files[0:100])
#feature, labels, groups = parse_audio_files(audio_files[0:100])
#print(np.array(feature).shape,feature,"\n\n",np.array(labels).shape,labels,"\n\n",np.array(groups).shape,groups,"\n\n")



for i in range(1):
    
    files = audio_files[i*1000: (i+1)*1000]
    print(files)
    X,y, groups = parse_audio_files(files)
    print("X >>",X, "\n\n","y >> ", y ,"\n\n","groups >> ", groups,"\n\n")
        
    
    print(files)
    X,y, groups = parse_audio_files(files)
    
    for r in y:
        if np.sum(r) > 1.5:
            print('error occured')
            break
    #np.savez('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/f_DATASET_%d.npz'%i,X=X,y=y,groups=groups)


['/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/70098-3-3-0.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/96921-9-0-9.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/72723-3-0-0.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/69777-3-0-2.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/79089-0-0-135.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/98859-7-2-0.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/96921-9-0-18.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/75743-0-0-2.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/75743-0-0-13.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/fold9/79584-3-0-8.wav', '/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/au

In [9]:
train = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/Final_DATASET_1.npz')
print(train)

In [10]:
for i in train:
    print(i)

X
y
groups


In [11]:
print(train['X'].shape,train['X'])
print(train['y'].shape,train['y'])
print(train['groups'].shape,train['groups'])

(1000, 193) [[-3.15714815e+02  1.30900646e+02 -3.34751739e+01 ...  3.40853965e-02
  -3.86813845e-03  5.79380516e-03]
 [-3.74507061e+02  1.48227058e+02 -1.03112501e+01 ... -5.02245595e-02
   3.06729875e-02  1.63803786e-03]
 [-1.94588387e+02  1.00814432e+02  3.31467270e+01 ... -1.64992869e-01
   4.31634481e-02  1.05443115e-02]
 ...
 [-6.78658518e+01  8.87490199e+01 -5.16569453e+01 ...  2.19029482e-01
  -7.30224610e-03  4.68377294e-02]
 [ 2.00258578e+02  1.66600743e+01  4.46145707e-01 ...  3.24249172e-02
   3.44625965e-02  2.02357838e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
(1000,) [8. 0. 0. 7. 0. 4. 7. 4. 5. 2. 3. 4. 9. 0. 7. 0. 4. 8. 9. 5. 2. 6. 5. 9.
 2. 4. 4. 2. 8. 9. 8. 9. 3. 3. 3. 9. 9. 4. 7. 4. 9. 5. 8. 3. 0. 7. 8. 9.
 1. 0. 6. 4. 0. 3. 2. 2. 4. 9. 4. 7. 4. 3. 4. 6. 1. 1. 9. 5. 6. 3. 7. 4.
 5. 1. 3. 6. 9. 8. 9. 7. 6. 1. 8. 0. 6. 7. 9. 3. 3. 3. 3. 6. 7. 3. 4. 7.
 9. 3. 0. 0. 0. 4. 7. 7. 8. 8. 0. 5. 5. 6. 9. 1. 4. 