In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.utils as utils
import torchvision.datasets as dsets
import torchvision.transforms as transforms

import numpy as np
import random
import os
from torch.utils.data import Dataset, DataLoader
import data_provider2

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.utils as utils
import torchvision.datasets as dsets
import torchvision.transforms as transforms

import numpy as np
import random
import os
from torch.utils.data import Dataset, DataLoader
import data_provider2




class my_datset2(Dataset):
    
    
    def __init__(self,train = True):
        
        
        self.train = train

        total_train = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/total_train_dataset.npz',dtype=np.float32)
        total_test = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/total_test_dataset.npz',dtype=np.float32)
        
                      
   
        if self.train :
            
            x=np.array([0,0,0,0,0,0,0])
            self.train_data = np.zeros((6530,200))
            self.train_data ,self.train_label = total_train['X'], total_train['y']
              
            
            for i in range(len(self.train_data)):
                self.train_data[i,] =  np.concatenate((self.train_data[i,],x),axis=None)
            
            
            self.train_data =self.train_data .reshape(6530,1,10,20)
            dtype = torch.FloatTensor
            self.train_data  = torch.as_tensor(self.train_data ).type(dtype)
            
            
            
           
            self.train_label = np.array(self.train_label)
            
            self.train_label = torch.tensor(self.train_label, dtype=torch.long)


                
        else :
            
            
            x=np.array([0,0,0,0,0,0,0])
            self.test_data = np.zeros((1722,200))
            self.test_data ,self.test_label = total_test['X'], total_test['y']
              
            
            for i in range(len(self.test_data)):
                self.test_data[i,] =  np.concatenate((self.test_data[i,],x),axis=None)
            
            
            self.test_data =self.test_data .reshape(1722,1,10,20)
            dtype = torch.FloatTensor
            self.train_data  = torch.as_tensor(self.train_data ).type(dtype)
            
            
            
           
            self.test_label = np.array(self.test_label)
            
            self.test_label = torch.tensor(self.test_label, dtype=torch.long)
 
    
    
    
    def __getitem__(self,idx):
            
        if self.train :
            
            data , target = self.train_data[idx], self.train_label[idx]
            
        else:
                
            data, target = self.test_data[idx], self.test_label[idx]
                
        
        
        return data, target
    

                
                
                
                
    
    def __len__(self):
        
            
        if self.train:
            return len(self.train_data)
            
        
        else:
            return len(self.test_data)
            

    
    
    

In [67]:
total_train = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/total_train_dataset.npz')
total_test = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/total_test_dataset.npz')
total_train =total_train['X'] 
total_test = total_test['X']
print(total_test.shape)
#total_train_target = total_train['y']

(1722, 193)


In [65]:
total_train = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/total_train_dataset.npz') 
toto2 =total_train['y'] 
print(total_train['y'])
train_label = np.array(toto2)
            
toto2 = torch.tensor(toto2, dtype=torch.long)
print(toto2)
print(toto2.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
tensor([[1, 0, 0,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])
torch.Size([6530, 11])


In [22]:
total_train=total_train.reshape(6530,1,10,20)

ValueError: cannot reshape array of size 1260290 into shape (6530,1,10,20)

In [24]:
dtype = torch.FloatTensor
total_train = torch.as_tensor(total_train).type(dtype)

In [ ]:
total_train.view(10,20)

In [26]:
total_train.shape

torch.Size([6530, 193])

In [45]:
print(total_train[1,].shape)
print(total_train.type())
print(total_train[1,].dtype)
print(len(total_train))

x = torch.zeros(1, 7,dtype=torch.float32)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

(193,)


AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [52]:
x=np.array([0,0,0,0,0,0,0])
toto = np.zeros((6530,200))

In [69]:
x=np.array([0,0,0,0,0,0,0])
toto = np.zeros((6530,200))
for i in range(len(total_train)):
    toto[i,] =  np.concatenate((total_train[i,],x),axis=None)
    

In [71]:
toto.shape

(6530, 200)

In [57]:
total_train2=toto.reshape(6530,1,10,20)
dtype = torch.FloatTensor
total_train2 = torch.as_tensor(total_train2).type(dtype)
total_train2=total_train2.reshape(6530,1,10,20)

In [59]:
total_train2.shape

torch.Size([6530, 1, 10, 20])

In [72]:
x=np.array([0,0,0,0,0,0,0])
toto = np.zeros((6530,200))
for i in range(len(total_train)):
    toto[i,] =  np.concatenate((total_train[i,],x),axis=None)
total_train2=toto.reshape(6530,1,10,20)
dtype = torch.FloatTensor
total_train2 = torch.as_tensor(total_train2).type(dtype)
total_train2=total_train2.reshape(6530,1,10,20)

In [73]:
total_train2.shape

torch.Size([6530, 1, 10, 20])