In [1]:
import numpy as np
from sklearn.model_selection import GroupShuffleSplit



In [6]:
sound_data = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/Final_totaldataset.npz')
X_data = sound_data['X']
y_data = sound_data['y'][1:8253]
groups = sound_data['groups']

print(groups[groups > 0])

[177537. 164797.  27216. ... 203929. 169098. 106015.]


In [7]:
gss = GroupShuffleSplit(n_splits=1,test_size=0.2)

for train_idx ,test_idx in gss.split(X_data , y_data, groups = groups):
    X_train = X_data[train_idx]
    y_train = y_data[train_idx]
    groups_train = groups[train_idx]
    
    X_test = X_data[test_idx]
    y_test = y_data[test_idx]
    groups_test = groups[test_idx]
    
    print("X_train.shape >> ",X_train.shape ,"\n\n", "X_test.shape >>", X_test.shape)
    
np.savez('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/Final_train_dataset.npz',X=X_train, y=y_train, groups=groups_train)
np.savez('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/Final_test_dataset.npz',X=X_test, y=y_test, groups=groups_test)


X_train.shape >>  (6723, 193) 

 X_test.shape >> (1529, 193)


In [8]:
train = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/total_train_dataset.npz')
test = np.load('/home/libedev/mute/mute-hero/download/urbansound/UrbanSound8K/audio/total_test_dataset.npz')

In [34]:
print(train['y'],"\n\n")
print(test['y'].shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 


(1722, 11)
