In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import librosa

import torchvision
import torchvision.utils as utils
import torchvision.datasets as dsets
import torchvision.transforms as transforms

import numpy as np
import random
import os
import pandas as pd
import data_provider

In [33]:
root = '/home/libedev/mute/mute-hero/download/dataset/'+'new_train'+'/'
        
option = 'spectrum_Stft'+'/'
option2 = 'new_train_label'

all_files = os.path.join(root,option)
        

    
data=[os.path.join(dirpath,f)for dirpath, dirnames, filenames in os.walk(all_files) for f in filenames]         
        
train_data =[]
            
X = np.zeros((400, 188, 513,1))            

train_label=np.load('/home/libedev/mute/mute-hero/download/dataset/'+str(option2)+'.npy')
        
test_data =[]
                   
test_label = np.load('/home/libedev/mute/mute-hero/download/dataset/new_test_label.npy')


for f in data:
    
        
    
    train_data.append(np.load(f))
    print(np.load(f).shape)
    #X[400, :, :, 0] = 
    

    
#print(np.stack(train_data,axis=1))    
        
#train_data = np.array(train_data) 

#train_data = np.array([train_data] )
#train_data = np.concatenate(train_data)   


#train_data = np.reshape(400,513,517)
'''
train_data = np.array([train_data] ,dtype = np.float32)
#train_data = train_data.transpose((1,0,2,3))
#dtype = torch.FloatTensor

train_data = torch.as_tensor(train_data)


train_data = train_data.squeeze()
#print(train_data.dtype)

train_label = torch.as_tensor(np.array(train_label))
           

'''





(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(157, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)
(188, 513)

'\ntrain_data = np.array([train_data] ,dtype = np.float32)\n#train_data = train_data.transpose((1,0,2,3))\n#dtype = torch.FloatTensor\n\ntrain_data = torch.as_tensor(train_data)\n\n\ntrain_data = train_data.squeeze()\n#print(train_data.dtype)\n\ntrain_label = torch.as_tensor(np.array(train_label))\n           \n\n'

In [34]:
print(train_data[0].shape)
print(train_data[0],"\n\n")
print(train_data[0][:188,:513])

(188, 513)
[[2.520026   1.1651455  2.699919   ... 0.09457788 0.05136547 0.03414348]
 [1.2919885  2.4925942  3.420761   ... 0.79992175 0.38674802 0.15731676]
 [4.542751   4.959055   5.3557844  ... 1.2623873  0.60130095 0.14861593]
 ...
 [3.6028256  3.8428216  4.030156   ... 0.10807085 0.1333492  0.10639933]
 [1.6390579  4.3816147  5.3440804  ... 2.204644   2.2124832  2.2022808 ]
 [4.8908963  3.9805117  5.308063   ... 3.863593   3.8632705  3.8635242 ]] 


[[2.520026   1.1651455  2.699919   ... 0.09457788 0.05136547 0.03414348]
 [1.2919885  2.4925942  3.420761   ... 0.79992175 0.38674802 0.15731676]
 [4.542751   4.959055   5.3557844  ... 1.2623873  0.60130095 0.14861593]
 ...
 [3.6028256  3.8428216  4.030156   ... 0.10807085 0.1333492  0.10639933]
 [1.6390579  4.3816147  5.3440804  ... 2.204644   2.2124832  2.2022808 ]
 [4.8908963  3.9805117  5.308063   ... 3.863593   3.8632705  3.8635242 ]]


In [94]:
import numpy as np
import random
    
    
    
def prepare_data():
    
        
    global train_samples, train_labels, test_samples, test_labels

    train_samples = open('/home/libedev/mute/mute-hero/download/dataset/new_train_samples.txt').read().strip().split('\n')
    train_labels = [int(label) for label in open('/home/libedev/mute/mute-hero/download/dataset/new_train_labels.txt').read().strip().split('\n')]     

    test_samples = open('/home/libedev/mute/mute-hero/download/dataset/new_test_samples.txt').read().strip().split('\n')
    test_labels = [int(label) for label in open('/home/libedev/mute/mute-hero/download/dataset/new_test_labels.txt').read().strip().split('\n')]
 

  
def get_random_sample(part):
    
    global train_samples, train_labels, test_samples, test_labels
    
    option = 'spectrum_Stft'
    
    train_samples = open('/home/libedev/mute/mute-hero/download/dataset/new_train_samples.txt').read().strip().split('\n')
    train_labels = [int(label) for label in open('/home/libedev/mute/mute-hero/download/dataset/new_train_labels.txt').read().strip().split('\n')]     


    test_samples = open('/home/libedev/mute/mute-hero/download/dataset/new_test_samples.txt').read().strip().split('\n')
    test_labels = [int(label) for label in open('/home/libedev/mute/mute-hero/download/dataset/new_test_labels.txt').read().strip().split('\n')]

      
    if part == 'new_train':
        
        samples = train_samples
        labels = train_labels    
        
    elif part == 'new_test':
        
        samples = test_samples
        labels = test_labels
        
    else :
        
        print('Please use train, valid, or test for the part name')

    i = random.randrange(len(samples))
    spectrum = np.load('/home/libedev/mute/mute-hero/download/dataset/'
                           +str(part)+'/'+str(option)+'/'+samples[i]+'.npy')
        
        
    return spectrum, labels[i]        

    
    
def get_random_batch(part):
    global train_samples, train_labels, test_samples, test_labels
    
    option = 'spectrum_Stft'
    data_amount = len(train_samples)
    example_data = np.load('/home/libedev/mute/mute-hero/download/dataset/'
                           +str(part)+'/'+str(option)+'/'+train_samples[0]+'.npy')
    
    X = np.zeros((data_amount, example_data.shape[0], example_data.shape[1], 1))
    Y = np.zeros((data_amount,))
    
    for i in range(0,data_amount):
        
        s,l = get_random_sample(part)
        
        X[i, :, :, 0] = s[:example_data.shape[0], :example_data.shape[1]]
        Y[i] =  l
    
    return X,Y




In [95]:
len(train_samples)

398

In [88]:
prepare_data()
a=get_random_batch('new_train')
a.shape
a

array([[[[7.47154903],
         [7.58441114],
         [6.94122028],
         ...,
         [2.79154086],
         [2.75206995],
         [2.66626811]],

        [[6.59289789],
         [6.99896336],
         [7.7353673 ],
         ...,
         [2.25218606],
         [2.14826941],
         [1.93538988]],

        [[6.39544582],
         [6.02739286],
         [6.9327445 ],
         ...,
         [0.68089902],
         [0.56137609],
         [0.5873701 ]],

        ...,

        [[6.2787118 ],
         [7.03006315],
         [7.70038795],
         ...,
         [0.0336301 ],
         [0.03674597],
         [0.09995387]],

        [[3.89220262],
         [5.7737689 ],
         [7.48149204],
         ...,
         [0.45256343],
         [0.47661433],
         [0.40829366]],

        [[7.20354605],
         [7.26388121],
         [7.76164532],
         ...,
         [1.46209502],
         [1.45756996],
         [1.44565451]]],


       [[[4.77525377],
         [4.66300821],
         [2.30

In [43]:
train_samples = open('/home/libedev/mute/mute-hero/download/dataset/new_train_samples.txt').read().strip().split('\n')
count =0 
for i in range(0,400):
    i = random.randrange(len(train_samples))
    print(i)
    count +=1
    
print("\n\n\n")
print(count)

35
35
36
394
208
65
350
217
229
36
302
303
367
192
126
111
367
334
310
310
79
35
376
260
210
71
259
8
245
20
44
335
14
8
328
110
164
165
301
304
156
187
1
330
377
168
100
147
171
177
319
315
98
120
56
193
359
105
201
382
216
169
208
384
355
270
231
196
64
12
220
301
25
311
124
380
115
156
334
363
324
338
60
69
246
0
26
256
348
136
176
371
199
114
205
121
330
386
358
203
271
357
12
332
144
325
216
344
95
246
271
217
295
181
63
135
312
294
226
171
180
173
218
175
385
83
116
172
180
155
385
144
51
279
20
24
307
84
139
366
18
388
367
235
1
229
39
66
67
240
282
375
55
308
324
149
264
86
117
256
265
258
66
45
245
174
75
345
285
76
164
291
389
319
109
221
187
278
308
94
96
8
381
221
233
294
371
264
135
26
227
181
220
126
287
276
326
175
155
195
207
232
32
104
94
47
359
194
51
336
146
142
392
146
354
25
134
123
4
163
168
127
390
159
236
104
219
147
329
356
372
213
169
306
246
98
319
365
381
160
150
132
150
308
280
386
290
146
55
283
118
23
37
71
120
204
390
21
312
189
207
91
278
382
330
84
328

In [92]:
def sample():
    train_samples = open('/home/libedev/mute/mute-hero/download/dataset/new_train_samples.txt').read().strip().split('\n')
    option = 'spectrum_Stft'
    i = random.randrange(len(train_samples))
    spectrum = np.load('/home/libedev/mute/mute-hero/download/dataset/'
                           +'new_train'+'/'+str(option)+'/'+train_samples[i]+'.npy')
        
        
    return spectrum        


#a=np.load('/home/libedev/mute/mute-hero/download/dataset/new_train/spectrum_Stft/train_Laughter_4.npy')
print(a.shape)
z  = np.zeros((400,188,513,1))


for i in range(0,1):
    
    a = sample()
    z[i, :, :,0]= a[ :188, :513] 
    

    
print(z , "\n\n" , z.shape[3])

(188, 513)
[[[[3.73120284e+00]
   [3.61468983e+00]
   [3.22580910e+00]
   ...
   [6.26367808e-04]
   [1.34389661e-03]
   [1.61993352e-03]]

  [[5.04514408e+00]
   [5.81243801e+00]
   [6.66516542e+00]
   ...
   [6.90475777e-02]
   [3.93515676e-02]
   [2.72864737e-02]]

  [[5.81480598e+00]
   [5.99077082e+00]
   [6.98815536e+00]
   ...
   [1.55150279e-01]
   [9.73178372e-02]
   [1.70613658e-02]]

  ...

  [[4.38388443e+00]
   [5.40024185e+00]
   [6.86337185e+00]
   ...
   [5.15879616e-02]
   [1.94965422e-01]
   [2.32410163e-01]]

  [[2.88342857e+00]
   [5.72847843e+00]
   [6.80779266e+00]
   ...
   [1.62029409e+00]
   [1.69514453e+00]
   [1.64014900e+00]]

  [[4.89335728e+00]
   [4.97357702e+00]
   [5.40855932e+00]
   ...
   [3.24737978e+00]
   [3.24883866e+00]
   [3.24817419e+00]]]


 [[[0.00000000e+00]
   [0.00000000e+00]
   [0.00000000e+00]
   ...
   [0.00000000e+00]
   [0.00000000e+00]
   [0.00000000e+00]]

  [[0.00000000e+00]
   [0.00000000e+00]
   [0.00000000e+00]
   ...
   [0.0000

In [70]:
z  = np.zeros((400,188,513,1))
for i in range(0,399):
    print(z[i,:,:,0],z[i,:,:,0].shape,"\n")
    a= sample()
    print(a[ :188, :513] ,a[ :188, :513].shape,"\n")
    z[i,:,:,0] = a[:188,:513]
    print(z, z.shape,"\n\n\n")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (188, 513) 

[[6.0599794  5.8163157  5.570064   ... 2.0004911  2.0001106  1.9855424 ]
 [5.1455045  5.6655545  6.206548   ... 1.4503899  1.4398799  1.40385   ]
 [4.702151   5.2520247  5.5646224  ... 0.15281898 0.11308045 0.02969545]
 ...
 [4.8140893  4.6260986  4.12182    ... 0.01825777 0.01980822 0.01586048]
 [5.407067   4.0872545  4.7403903  ... 0.39985418 0.4148951  0.41476047]
 [6.2678432  6.1085916  6.144041   ... 1.3567016  1.3638811  1.3665564 ]] (188, 513) 

[[[[6.05997944]
   [5.81631565]
   [5.57006407]
   ...
   [2.00049114]
   [2.00011063]
   [1.98554242]]

  [[5.14550447]
   [5.66555452]
   [6.20654821]
   ...
   [1.45038986]
   [1.43987989]
   [1.40384996]]

  [[4.70215082]
   [5.25202465]
   [5.5646224 ]
   ...
   [0.15281898]
   [0.11308045]
   [0.02969545]]

  ...

  [[4.8140893 ]
   [4.62609863]
   [4.12181997]
   .

ValueError: could not broadcast input array from shape (157,513) into shape (188,513)

In [62]:
for i in range(0,10):
    
    print(z)
z.shape

[[[[6.97296953e+00]
   [4.66900682e+00]
   [6.19758177e+00]
   ...
   [1.50365663e+00]
   [1.50128329e+00]
   [1.50276279e+00]]

  [[7.58599281e+00]
   [7.10879326e+00]
   [5.21348000e+00]
   ...
   [1.02478027e+00]
   [9.92737651e-01]
   [1.02699113e+00]]

  [[8.10125446e+00]
   [7.66504478e+00]
   [6.73327446e+00]
   ...
   [4.24121059e-02]
   [1.14781775e-01]
   [1.41234890e-01]]

  ...

  [[7.38790751e+00]
   [6.95095158e+00]
   [6.84305620e+00]
   ...
   [1.92633390e-01]
   [1.76977888e-01]
   [4.32682261e-02]]

  [[7.95345259e+00]
   [7.27833700e+00]
   [6.41633177e+00]
   ...
   [2.09964347e+00]
   [2.08989167e+00]
   [2.11440945e+00]]

  [[8.41205311e+00]
   [7.91318130e+00]
   [6.71253872e+00]
   ...
   [3.72514915e+00]
   [3.73411226e+00]
   [3.73784661e+00]]]


 [[[8.00629520e+00]
   [6.12470722e+00]
   [6.65681314e+00]
   ...
   [4.73781681e+00]
   [4.73413515e+00]
   [4.73114300e+00]]

  [[7.90899324e+00]
   [8.34504032e+00]
   [8.74778080e+00]
   ...
   [4.05577469e+00]
 

(10, 188, 513, 1)

In [72]:
a=np.load('/home/libedev/mute/mute-hero/download/dataset/new_train/spectrum_Stft/train_WomanSpeech_50.npy')

In [73]:
a.shape

(157, 513)