In [53]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.utils as utils
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.autograd import Variable
import numpy as np
import random
import os

In [54]:

import matplotlib.pyplot as plt
%matplotlib inline

In [55]:
mnist_train = dsets.MNIST(root='data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

In [56]:
batch_size = 100

train_loader  = torch.utils.data.DataLoader(dataset=mnist_train,
                                           batch_size=batch_size,
                                           shuffle=False)

test_loader = torch.utils.data.DataLoader(dataset=mnist_test,
                                         batch_size=batch_size,
                                         shuffle=False)

In [57]:
print(train_loader)

In [58]:
print(mnist_train.train_data.shape)
print(mnist_train.train_labels.shape)

torch.Size([60000, 28, 28])
torch.Size([60000])


/home/libedev/anaconda3/envs/mute/lib/python3.6/site-packages/torchvision/datasets/mnist.py:43: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


In [59]:
print(mnist_test.train_data)

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [10]:
for i in range(0,5):
    print(mnist_train.train_labels)

tensor([5, 0, 4,  ..., 5, 6, 8])
tensor([5, 0, 4,  ..., 5, 6, 8])
tensor([5, 0, 4,  ..., 5, 6, 8])
tensor([5, 0, 4,  ..., 5, 6, 8])
tensor([5, 0, 4,  ..., 5, 6, 8])


In [11]:
for i in range(0,5):
    print(mnist_train.train_data[i].shape)

torch.Size([28, 28])
torch.Size([28, 28])
torch.Size([28, 28])
torch.Size([28, 28])
torch.Size([28, 28])


In [89]:
for i in range(0,5):
    print(mnist_train.train_data[i])

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
          18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

In [50]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        
        self.layer = nn.Sequential(
            nn.Conv2d(1,16,5),
            nn.ReLU(),
            nn.Conv2d(16,32,5),
            nn.ReLU(),
            nn.MaxPool2d(2,2),
            nn.Conv2d(32,64,5),
            nn.ReLU(),
            nn.MaxPool2d(2,2)
        )
        
        self.fc_layer = nn.Sequential(
            nn.Linear(64*3*3,100),
            nn.ReLU(),
            nn.Linear(100,10)
        )       
        
    def forward(self,x):
        print(x.data.shape)
        out = self.layer(x)
        out = out.view(out.shape[0],-1)
        out = self.fc_layer(out)

        return out

In [52]:
a= torch.rand(400,1,28,28)
a = Variable(a)
network = CNN()
out = network(a)
print(out.shape)

torch.Size([400, 1, 28, 28])
torch.Size([400, 10])


In [43]:

model = CNN().cuda()

In [44]:
loss = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [45]:

num_epochs = 5

In [46]:
save_path =  '/home/libedev/mute/mute-hero/download/dataset/model2/'
model_path = save_path + 'model2.pkl'

In [47]:
if not os.path.exists(save_path):
    os.makedirs(save_path)

In [48]:
if os.path.isfile(model_path):
    model.load_state_dict(torch.load(model_path))
    print("Model Loaded!")

else:
    
    for epoch in range(num_epochs):

        total_batch = len(mnist_train) // batch_size

        for i, (batch_images, batch_labels) in enumerate(train_loader):

            X = batch_images.cuda()
            Y = batch_labels.cuda()

            pre = model(X)
            cost = loss(pre, Y)

            optimizer.zero_grad()
            cost.backward()
            optimizer.step()

            if (i+1) % 100 == 0:
                print('Epoch [%d/%d], lter [%d/%d], Loss: %.4f'
                     %(epoch+1, num_epochs, i+1, total_batch, cost.item()))

    if not os.path.isfile(model_path):
        print("Model Saved!")
        torch.save(model.state_dict(), model_path)

Epoch [1/5], lter [100/600], Loss: 0.4803
Epoch [1/5], lter [200/600], Loss: 0.2691
Epoch [1/5], lter [300/600], Loss: 0.1733
Epoch [1/5], lter [400/600], Loss: 0.1046
Epoch [1/5], lter [500/600], Loss: 0.1050
Epoch [1/5], lter [600/600], Loss: 0.3001
Epoch [2/5], lter [100/600], Loss: 0.0237
Epoch [2/5], lter [200/600], Loss: 0.0544
Epoch [2/5], lter [300/600], Loss: 0.0369
Epoch [2/5], lter [400/600], Loss: 0.0210
Epoch [2/5], lter [500/600], Loss: 0.0782
Epoch [2/5], lter [600/600], Loss: 0.2550
Epoch [3/5], lter [100/600], Loss: 0.0124
Epoch [3/5], lter [200/600], Loss: 0.0310
Epoch [3/5], lter [300/600], Loss: 0.0222
Epoch [3/5], lter [400/600], Loss: 0.0119
Epoch [3/5], lter [500/600], Loss: 0.0562
Epoch [3/5], lter [600/600], Loss: 0.2228
Epoch [4/5], lter [100/600], Loss: 0.0086
Epoch [4/5], lter [200/600], Loss: 0.0234
Epoch [4/5], lter [300/600], Loss: 0.0174
Epoch [4/5], lter [400/600], Loss: 0.0116
Epoch [4/5], lter [500/600], Loss: 0.0451
Epoch [4/5], lter [600/600], Loss:

In [58]:
print(data_loader)

In [82]:
for i in range(3) :
    batch_images, batch_labels = next(iter(train_loader))
    print(batch_labels.numpy(), ", ", len(batch_labels.numpy()))

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 6 9 0 5 6
 0 7 6 1 8 7 9 3 9 8 5 9 3 3 0 7 4 9 8 0 9 4 1 4 4 6 0 4 5 6 1 0 0 1 7 1 6
 3 0 2 1 1 7 9 0 2 6 7 8 3 9 0 4 6 7 4 6 8 0 7 8 3 1] ,  100
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 6 9 0 5 6
 0 7 6 1 8 7 9 3 9 8 5 9 3 3 0 7 4 9 8 0 9 4 1 4 4 6 0 4 5 6 1 0 0 1 7 1 6
 3 0 2 1 1 7 9 0 2 6 7 8 3 9 0 4 6 7 4 6 8 0 7 8 3 1] ,  100
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 6 9 0 5 6
 0 7 6 1 8 7 9 3 9 8 5 9 3 3 0 7 4 9 8 0 9 4 1 4 4 6 0 4 5 6 1 0 0 1 7 1 6
 3 0 2 1 1 7 9 0 2 6 7 8 3 9 0 4 6 7 4 6 8 0 7 8 3 1] ,  100


In [60]:
batch_images.shape

torch.Size([100, 1, 28, 28])

In [66]:
print(batch_images[99].shape)
print(batch_images.shape)

torch.Size([1, 28, 28])
torch.Size([100, 1, 28, 28])


In [67]:
print(batch_labels[99].shape)
print(batch_labels.shape)

torch.Size([])
torch.Size([100])


In [70]:
print(batch_labels)
print(len(batch_labels))

tensor([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9, 1,
        1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9, 8, 5,
        9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0, 0, 1, 7,
        1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7, 4, 6, 8, 0,
        7, 8, 3, 1])
100
