In [62]:
import numpy as np
from sklearn import preprocessing
import os
import librosa
import torch 

In [63]:
label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

In [167]:
a=np.genfromtxt('/home/libedev/mute/mute-hero/download/dataset/new_train_labels.txt', encoding='ascii',dtype=int)


In [168]:
print(a)
print(len(a))

#np.save("/home/libedev/mute/mute-hero/download/dataset/new_test_label.npy",a)

[7 7 4 4 0 6 7 5 1 2 7 6 6 2 5 3 0 7 7 4 5 3 3 1 0 1 3 7 3 5 6 0 3 0 1 3 0
 7 0 2 2 0 3 4 4 4 4 7 3 4 2 7 0 7 0 0 5 2 3 5 7 5 1 7 3 6 4 5 2 0 4 3 1 4
 6 1 7 1 2 2 2 1 3 7 7 6 0 7 0 3 6 3 1 0 5 4 4 3 5 3 1 7 5 2 0 6 0 7 4 4 1
 1 6 3 0 1 1 3 5 7 7 5 0 5 7 2 6 4 3 4 3 1 7 2 4 4 7 1 0 4 5 7 3 4 0 1 7 3
 0 7 6 4 3 6 2 2 2 6 2 0 7 7 6 6 1 5 4 5 5 4 3 4 4 4 6 7 5 3 3 6 5 6 2 1 7
 3 2 0 0 1 7 0 0 0 6 6 1 6 1 2 1 6 5 7 2 5 3 3 3 1 4 0 2 3 7 7 5 3 1 7 1 0
 1 7 6 0 4 2 2 0 5 0 7 1 4 6 7 3 5 6 0 0 4 5 4 3 2 6 0 2 5 3 4 4 2 2 3 5 2
 6 1 4 1 6 3 7 2 5 2 6 7 5 6 4 2 5 6 2 2 3 5 2 4 2 5 6 4 0 5 1 2 3 5 4 5 0
 1 7 1 4 4 4 3 3 4 6 6 0 3 5 6 1 2 4 4 6 0 6 2 3 3 4 7 2 3 3 6 1 5 4 2 2 5
 0 0 6 5 1 1 6 1 6 4 4 2 0 5 2 1 3 0 1 1 1 1 5 2 2 0 0 5 5 0 1 7 7 1 0 7 3
 7 7 6 5 2 0 6 0 6 1 1 6 4 2 5 1 6 7 5 5 5 6 6 2 6 2 7 5 1 3]
400


## 여기서 부터 numpy 시작

In [150]:
c=[]

In [151]:
d = c.append(np.load('/home/libedev/mute/mute-hero/download/dataset/new_train_label.npy'))

In [153]:
d

In [154]:
c = np.load('/home/libedev/mute/mute-hero/download/dataset/new_train_label.npy')

In [155]:
c

array([7, 7, 4, 4, 0, 6, 7, 5, 1, 2, 7, 6, 6, 2, 5, 3, 0, 7, 7, 4, 5, 3,
       3, 1, 0, 1, 3, 7, 3, 5, 6, 0, 3, 0, 1, 3, 0, 7, 0, 2, 2, 0, 3, 4,
       4, 4, 4, 7, 3, 4, 2, 7, 0, 7, 0, 0, 5, 2, 3, 5, 7, 5, 1, 7, 3, 6,
       4, 5, 2, 0, 4, 3, 1, 4, 6, 1, 7, 1, 2, 2, 2, 1, 3, 7, 7, 6, 0, 7,
       0, 3, 6, 3, 1, 0, 5, 4, 4, 3, 5, 3, 1, 7, 5, 2, 0, 6, 0, 7, 4, 4,
       1, 1, 6, 3, 0, 1, 1, 3, 5, 7, 7, 5, 0, 5, 7, 2, 6, 4, 3, 4, 3, 1,
       7, 2, 4, 4, 7, 1, 0, 4, 5, 7, 3, 4, 0, 1, 7, 3, 0, 7, 6, 4, 3, 6,
       2, 2, 2, 6, 2, 0, 7, 7, 6, 6, 1, 5, 4, 5, 5, 4, 3, 4, 4, 4, 6, 7,
       5, 3, 3, 6, 5, 6, 2, 1, 7, 3, 2, 0, 0, 1, 7, 0, 0, 0, 6, 6, 1, 6,
       1, 2, 1, 6, 5, 7, 2, 5, 3, 3, 3, 1, 4, 0, 2, 3, 7, 7, 5, 3, 1, 7,
       1, 0, 1, 7, 6, 0, 4, 2, 2, 0, 5, 0, 7, 1, 4, 6, 7, 3, 5, 6, 0, 0,
       4, 5, 4, 3, 2, 6, 0, 2, 5, 3, 4, 4, 2, 2, 3, 5, 2, 6, 1, 4, 1, 6,
       3, 7, 2, 5, 2, 6, 7, 5, 6, 4, 2, 5, 6, 2, 2, 3, 5, 2, 4, 2, 5, 6,
       4, 0, 5, 1, 2, 3, 5, 4, 5, 0, 1, 7, 1, 4, 4,

In [157]:
labels_data=[]
print(c.shape)
for i in c:
    labels_data.append(i)
    

(400,)


In [159]:
labels_data = np.array(labels_data)
labels_data = labels_data.reshape(400,1,1,1)

In [164]:
labels_data.shape

(400, 1, 1, 1)

In [161]:
f_x = torch.from_numpy(labels_data)

In [163]:
f_x

tensor([[[[7]]],


        [[[7]]],


        [[[4]]],


        [[[4]]],


        [[[0]]],


        [[[6]]],


        [[[7]]],


        [[[5]]],


        [[[1]]],


        [[[2]]],


        [[[7]]],


        [[[6]]],


        [[[6]]],


        [[[2]]],


        [[[5]]],


        [[[3]]],


        [[[0]]],


        [[[7]]],


        [[[7]]],


        [[[4]]],


        [[[5]]],


        [[[3]]],


        [[[3]]],


        [[[1]]],


        [[[0]]],


        [[[1]]],


        [[[3]]],


        [[[7]]],


        [[[3]]],


        [[[5]]],


        [[[6]]],


        [[[0]]],


        [[[3]]],


        [[[0]]],


        [[[1]]],


        [[[3]]],


        [[[0]]],


        [[[7]]],


        [[[0]]],


        [[[2]]],


        [[[2]]],


        [[[0]]],


        [[[3]]],


        [[[4]]],


        [[[4]]],


        [[[4]]],


        [[[4]]],


        [[[7]]],


        [[[3]]],


        [[[4]]],


        [[[2]]],


        [[[7]]],


        [[[0

In [129]:
x = torch.from_numpy(c)
x

tensor([7, 7, 4, 4, 0, 6, 7, 5, 1, 2, 7, 6, 6, 2, 5, 3, 0, 7, 7, 4, 5, 3, 3, 1,
        0, 1, 3, 7, 3, 5, 6, 0, 3, 0, 1, 3, 0, 7, 0, 2, 2, 0, 3, 4, 4, 4, 4, 7,
        3, 4, 2, 7, 0, 7, 0, 0, 5, 2, 3, 5, 7, 5, 1, 7, 3, 6, 4, 5, 2, 0, 4, 3,
        1, 4, 6, 1, 7, 1, 2, 2, 2, 1, 3, 7, 7, 6, 0, 7, 0, 3, 6, 3, 1, 0, 5, 4,
        4, 3, 5, 3, 1, 7, 5, 2, 0, 6, 0, 7, 4, 4, 1, 1, 6, 3, 0, 1, 1, 3, 5, 7,
        7, 5, 0, 5, 7, 2, 6, 4, 3, 4, 3, 1, 7, 2, 4, 4, 7, 1, 0, 4, 5, 7, 3, 4,
        0, 1, 7, 3, 0, 7, 6, 4, 3, 6, 2, 2, 2, 6, 2, 0, 7, 7, 6, 6, 1, 5, 4, 5,
        5, 4, 3, 4, 4, 4, 6, 7, 5, 3, 3, 6, 5, 6, 2, 1, 7, 3, 2, 0, 0, 1, 7, 0,
        0, 0, 6, 6, 1, 6, 1, 2, 1, 6, 5, 7, 2, 5, 3, 3, 3, 1, 4, 0, 2, 3, 7, 7,
        5, 3, 1, 7, 1, 0, 1, 7, 6, 0, 4, 2, 2, 0, 5, 0, 7, 1, 4, 6, 7, 3, 5, 6,
        0, 0, 4, 5, 4, 3, 2, 6, 0, 2, 5, 3, 4, 4, 2, 2, 3, 5, 2, 6, 1, 4, 1, 6,
        3, 7, 2, 5, 2, 6, 7, 5, 6, 4, 2, 5, 6, 2, 2, 3, 5, 2, 4, 2, 5, 6, 4, 0,
        5, 1, 2, 3, 5, 4, 5, 0, 1, 7, 1,

In [ ]:
f_x = torch.from_numpy()