In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.utils as utils
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.autograd import Variable


import numpy as np
import random
import os
import Pyclass 
import Pyclass2


from torch.utils.data import Dataset, DataLoader

# PyClass2 import 

In [107]:
sound_train = Pyclass2.my_datset2(root='new_train',option='Mel_S_pca',option2 = 'new_train_label',train = True)
                         

sound_test = Pyclass2.my_datset2(root='new_test',option='Mel_S_pca',option2 = 'new_test_label',train = False)

In [18]:
sound_train = Pyclass.my_datset2(part='new_train',option='spectrum_Stft',train = True)
                         

sound_test = Pyclass.my_datset2(part='new_test',option='spectrum_Stft',train = False)

In [19]:
batch_size = 10

train_loader  = DataLoader(dataset=sound_train,
                                           batch_size=batch_size,
                                           shuffle=False
                                           ,num_workers=1)

test_loader = DataLoader(dataset=sound_test,
                                         batch_size=batch_size,
                                         shuffle=False,
                        num_workers=1)

In [19]:
print(train_loader)

In [20]:
print(sound_train.train_data.shape)
print(sound_train.train_label.shape)
print(sound_train.train_data.dtype)

torch.Size([400, 1, 188, 513])
torch.Size([400])
torch.float32


In [21]:
print(sound_train.train_data)

tensor([[[[5.0237e+00, 5.9819e+00, 7.0831e+00,  ..., 2.7972e+00,
           2.7848e+00, 2.7840e+00],
          [6.1989e+00, 6.4422e+00, 6.5390e+00,  ..., 2.1583e+00,
           2.1468e+00, 2.1544e+00],
          [6.0693e+00, 6.3929e+00, 6.1777e+00,  ..., 3.7915e-01,
           3.1625e-01, 3.7368e-01],
          ...,
          [6.3835e+00, 6.3011e+00, 6.4780e+00,  ..., 6.7207e-01,
           6.3476e-01, 9.6744e-02],
          [7.1514e+00, 7.3386e+00, 7.2743e+00,  ..., 2.1414e+00,
           2.3417e+00, 2.2069e+00],
          [3.8876e+00, 7.3784e+00, 7.3314e+00,  ..., 3.9235e+00,
           3.9345e+00, 3.9269e+00]]],


        [[[1.1059e+00, 1.1513e+00, 1.2478e+00,  ..., 4.8614e-04,
           3.8843e-04, 3.4922e-04],
          [5.1853e+00, 5.2686e+00, 5.3791e+00,  ..., 1.6618e-02,
           1.5701e-02, 1.4724e-02],
          [6.1761e+00, 6.7862e+00, 6.8186e+00,  ..., 6.6817e-02,
           5.6028e-02, 2.0844e-02],
          ...,
          [4.4700e+00, 6.0324e+00, 6.2813e+00,  ..., 4.84

In [22]:

for i in range(0,2):
    
    print(sound_train.train_label)
    print(type(sound_train.train_label))
    

tensor([7, 1, 4, 1, 7, 0, 1, 2, 6, 0, 3, 6, 5, 6, 2, 1, 0, 7, 7, 4, 2, 1, 5, 1,
        6, 4, 0, 6, 4, 7, 6, 7, 0, 5, 2, 2, 6, 2, 7, 7, 2, 6, 5, 4, 6, 3, 0, 7,
        6, 6, 5, 2, 6, 0, 1, 5, 6, 0, 7, 5, 6, 7, 2, 2, 0, 3, 7, 3, 2, 3, 2, 4,
        2, 0, 6, 4, 2, 1, 0, 7, 2, 2, 0, 6, 4, 2, 1, 6, 5, 1, 3, 0, 3, 5, 4, 7,
        1, 5, 1, 6, 3, 3, 2, 2, 2, 3, 6, 5, 3, 2, 5, 6, 2, 2, 5, 7, 4, 3, 7, 1,
        6, 5, 5, 4, 2, 2, 5, 7, 5, 0, 1, 1, 1, 6, 7, 5, 7, 4, 0, 4, 1, 5, 7, 7,
        6, 5, 2, 7, 7, 7, 7, 0, 6, 4, 2, 4, 6, 6, 3, 2, 4, 5, 5, 3, 0, 6, 1, 7,
        0, 6, 6, 4, 6, 1, 7, 3, 4, 7, 4, 5, 3, 6, 0, 4, 5, 3, 5, 0, 1, 3, 3, 5,
        0, 6, 0, 4, 0, 1, 6, 5, 4, 0, 0, 5, 6, 6, 5, 5, 7, 1, 3, 6, 0, 7, 1, 7,
        6, 7, 7, 6, 6, 7, 1, 2, 4, 4, 7, 6, 4, 5, 4, 6, 6, 3, 6, 3, 6, 1, 4, 1,
        7, 3, 1, 3, 1, 6, 0, 7, 1, 0, 3, 0, 5, 4, 0, 5, 6, 7, 3, 2, 6, 1, 3, 4,
        7, 6, 4, 6, 7, 6, 7, 7, 6, 6, 4, 4, 7, 1, 4, 3, 3, 1, 5, 0, 4, 5, 3, 4,
        5, 6, 7, 3, 0, 2, 0, 1, 1, 3, 6,

In [23]:
for i in range(0,5):
    print(sound_train.train_data.shape)

torch.Size([400, 1, 188, 513])
torch.Size([400, 1, 188, 513])
torch.Size([400, 1, 188, 513])
torch.Size([400, 1, 188, 513])
torch.Size([400, 1, 188, 513])


In [24]:
for i in range(0,3):
    print(sound_train.train_data)

tensor([[[[5.0237e+00, 5.9819e+00, 7.0831e+00,  ..., 2.7972e+00,
           2.7848e+00, 2.7840e+00],
          [6.1989e+00, 6.4422e+00, 6.5390e+00,  ..., 2.1583e+00,
           2.1468e+00, 2.1544e+00],
          [6.0693e+00, 6.3929e+00, 6.1777e+00,  ..., 3.7915e-01,
           3.1625e-01, 3.7368e-01],
          ...,
          [6.3835e+00, 6.3011e+00, 6.4780e+00,  ..., 6.7207e-01,
           6.3476e-01, 9.6744e-02],
          [7.1514e+00, 7.3386e+00, 7.2743e+00,  ..., 2.1414e+00,
           2.3417e+00, 2.2069e+00],
          [3.8876e+00, 7.3784e+00, 7.3314e+00,  ..., 3.9235e+00,
           3.9345e+00, 3.9269e+00]]],


        [[[1.1059e+00, 1.1513e+00, 1.2478e+00,  ..., 4.8614e-04,
           3.8843e-04, 3.4922e-04],
          [5.1853e+00, 5.2686e+00, 5.3791e+00,  ..., 1.6618e-02,
           1.5701e-02, 1.4724e-02],
          [6.1761e+00, 6.7862e+00, 6.8186e+00,  ..., 6.6817e-02,
           5.6028e-02, 2.0844e-02],
          ...,
          [4.4700e+00, 6.0324e+00, 6.2813e+00,  ..., 4.84

# Define Model

In [25]:
class CNN(nn.Module):
    def __init__(self):
        
        super(CNN, self).__init__()
        
        self.layer = nn.Sequential(
            nn.Conv2d(in_channels = 1,out_channels=16,kernel_size = 5),
            nn.ReLU(),
            nn.Dropout2d(0.5),
            nn.Conv2d(in_channels=16,out_channels=32,kernel_size = 5),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2,2),
            nn.Conv2d(in_channels = 32,out_channels = 64,kernel_size = 5),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2,2)
            
        )
        
        
        self.fc_layer = nn.Sequential(
            nn.Linear(64*6*6,100),
            nn.ReLU(),
            nn.Linear(100,8),
            nn.Softmax()
        )       
        
    def forward(self,x):
        print(x.data.shape)
        out = self.layer(x)
        out = out.view(out.shape[0],-1)
        out = self.fc_layer(out)

        return out

In [8]:
class CNN2(nn.Module):
    
    def __init__(self):
        super(CNN2,self).__init__()
    
        self.layer1 = nn.Sequential(
            nn.Conv2d(1,16,5),
            nn.ReLU(inplace=True),
            nn.Conv2d(16,32,5),
            nn.ReLU(inplace=True),
            nn.Conv2d(32,64,5),
            nn.ReLU(inplace=True),
            nn.Conv2d(64,128,5),
            nn.MaxPool2d(2)
    )
        self.layer2_1 = nn.Sequential(
            nn.Conv2d(128,256,7,1,2),
            nn.Conv2d(256,64,5),
            nn.MaxPool2d(2)
    )
        self.layer2_2 = nn.Sequential(
            nn.Conv2d(128,256,5,1,1),
            nn.Conv2d(256,64,5),
            nn.MaxPool2d(2)
    )
        self.layer2_3 = nn.Sequential(
            nn.Conv2d(128,256,3),
            nn.Conv2d(256,64,5),
            nn.MaxPool2d(2)
    )
        self.fc_layer = nn.Sequential(
            nn.Linear(1*64*3*3,100),
            nn.ReLU(),
            nn.Linear(100,8),
            nn.Softmax()
    )       
    
    def forward(self,x):
        print(x.data.shape)
        x= self.layer1(x)
        x1 = self.layer2_1(x)
        x2 = self.layer2_2(x)
        x3 = self.layer2_3(x)
        x=torch.cat((x1,x2,x3),1)
        x= x.view(x.shape[0],-1)
        x=self.fc_layer(x)
        return x

In [26]:
a= torch.rand(400,1,40,40)
a = Variable(a)
network = CNN()
out = network(a)
print(out.shape)

torch.Size([400, 1, 40, 40])
torch.Size([400, 8])


In [27]:
a= torch.rand(400,1,40,40)
a = Variable(a)
network = CNN()
out = network(a)
print(out.shape)

torch.Size([400, 1, 40, 40])
torch.Size([400, 8])


In [28]:
model = CNN().cuda()

In [29]:
loss = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)

# train model_CNN

In [31]:
num_epochs = 200


In [32]:

save_path = '/home/libedev/mute/mute-hero/download/dataset/model/'
model_path = save_path + 'model.pkl'

In [33]:
if not os.path.exists(save_path):
    os.makedirs(save_path)

In [34]:
if os.path.isfile(model_path):
    model.load_state_dict(torch.load(model_path))
    print("Model Loaded!")

else:
    
    for epoch in range(num_epochs):

        total_batch = len(sound_train) // batch_size

        for i, (batch_images, batch_labels) in enumerate(train_loader):

            X = batch_images.cuda()
            Y = batch_labels.cuda()

            pre = model(X)
            cost = loss(pre, Y)

            optimizer.zero_grad()
            cost.backward()
            optimizer.step()

            if (i+1) % 10 == 0:
                print('Epoch [%d/%d], lter [%d/%d], Loss: %.4f'
                     %(epoch+1, num_epochs, i+1, total_batch, cost.item()))

    if not os.path.isfile(model_path):
        print("Model Saved!")
        torch.save(model.state_dict(), model_path)

torch.Size([10, 1, 188, 513])


RuntimeError: size mismatch, m1: [10 x 341248], m2: [2304 x 100] at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorMathBlas.cu:268

# Test Model

In [16]:
model.eval()

correct = 0
total = 0

for sound, labels in test_loader:
    
    sound = sound.cuda()
    outputs = model(sound)
    
    _, predicted = torch.max(outputs.data, 1)
    
    total += labels.size(0)
    correct += (predicted == labels.cuda()).sum()
    
print('Accuracy of test sound: %f %%' % (100 * float(correct) / total))

torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
torch.Size([10, 1, 40, 40])
Accuracy of test sound: 14.285714 %
