In [10]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.utils as utils
import torchvision.datasets as dsets
import torchvision.transforms as transforms

import numpy as np
import random
import os
from torch.utils.data import Dataset, DataLoader

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim

import torchvision
import torchvision.utils as utils
import torchvision.datasets as dsets
import torchvision.transforms as transforms

import numpy as np
import random
import os
from torch.utils.data import Dataset, DataLoader




class my_datset(Dataset):
    
    
    
    
    
    def __init__(self, root, option, train = True):
        
        # root -->  new_train , new_test
        self.root = '/home/libedev/mute/mute-hero/download/dataset/'+root+'/'
        
        # option --> 전처리 폴더명
        self.option = option+'/'
        
        
        #add = self.root + self.option
        
        all_files = os.path.join(self.root,self.option)
        
        data=[os.path.join(dirpath,f)for dirpath, dirnames, filenames in os.walk(all_files) for f in filenames] 
        
        if self.train :
            
            
            
            self.train_data =[]
            self.train_label =[]
            self.train_label = self.train_label.append(np.load('/home/libedev/mute/mute-hero/download/dataset/new_train_label.npy'))
            
            
            for f in data:
                
                self.train_data.append(np.load(f))
                
                
            
            self.train_data = self.train_data.reshape((self.train_data.shape[0],1,self.train_data.shape[1],self.train_data.shape[2]))
            self.train_data = self.train_data.transpose((0,2,3,1))
            
            
            #완성된 dataset , label
            self.train_data = torch.from_numpy(self.train_data)   
            self.train_label = torch.from_numpy(self.train_label)

                
        else :
            
            
            self.test_data =[]
            self.test_label =[]
            
            self.test_label = self.test_label.append(np.load('/home/libedev/mute/mute-hero/download/dataset/new_test_label.npy'))
            
            
            
            for f in data:
                
                self.test_data.append(np.load(f))

            
            self.test_data=self.test_data.reshape(self.test_data.shape[0],1,self.test_data.shape[1],self.test_data.shape[2])
            self.test_data = self.test_data.transpose((0,2,3,1))
            
            
            #완성된 dataset , label
            self.test_data = torch.from_numpy(self.test_data)
            self.test_label = torch.from_numpy(self.test_label)
                
                
                
                
    
    def __len__(self , index):
        
            
        if self.train:
            return len(self.train_data)
            
        
        else:
            return len(self.test_data)
            

    
    
    def __getitem__(self,idx):
            
        if self.train :
            
            data , target = self.train_data[index], self.train_label[index]
            
        else:
                
            data, target = self.test_data[index], self.test_label[index]
                
        return data, target
    
    
    

In [49]:

        
add =  '/home/libedev/mute/mute-hero/download/dataset/new_test/'
add2 = 'spectrum_Stft/'
        
all_files = os.path.join(add,add2)
a = []
data=[os.path.join(dirpath,f)for dirpath, dirnames, filenames in os.walk(all_files) for f in filenames]           
for f in data:          
    a.append(np.vstack((np.array(np.load(str(f))))))
    A = np.matrix(np.vstack((np.array(np.load(str(f))))))
                 

f_data = np.array(a)
s_data = np.array(A)
print(type(f_data))
print(type(s_data))
    



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
        
add =  '/home/libedev/mute/mute-hero/download/dataset/new_test/'
add2 = 'spectrum_Mel_PCA/'
        
all_files = os.path.join(add,add2)
a = []

data=[os.path.join(dirpath,f)for dirpath, dirnames, filenames in os.walk(all_files) for f in filenames] 
count =0
for f in data:
    
    #print("file 배열 ")
    #print(np.load(f), "\n\n")
    
    a.append(np.load(f))
    count +=1
    #print(a)


    
print(count)    
#a=np.concatenate(axis=0)
   



140


In [13]:
a

[array([[-5.10057159e-01, -3.40568977e-01, -1.42187588e-01,
          1.17703367e-01, -1.50586656e-01, -4.55437754e-01,
         -3.83866164e-01,  1.08062927e-01, -3.58476269e-01,
         -2.44647495e-02],
        [-4.88205795e-01, -2.86558018e-01, -1.02936139e-01,
          9.37470657e-02, -7.47668156e-02, -6.58129674e-01,
          1.10063451e+00,  1.31569378e-01, -1.36943091e-01,
         -2.27693860e+00],
        [-2.80360678e-01, -7.58470284e-02,  7.08738347e-03,
         -9.33609124e-02, -1.19666355e-01, -1.09431844e-01,
          5.79094993e-01, -1.14686900e+00, -4.40947027e-01,
         -1.20103156e+00],
        [-1.91112327e-01,  8.47054039e-03, -4.11658610e-01,
         -5.54608850e-01,  2.95336114e-01, -1.45669652e-01,
          4.13979567e+00, -1.16639780e+00, -5.71180102e-02,
          1.05346788e+00],
        [-4.20769581e-01, -1.40756793e-01, -2.50107978e-01,
         -1.04277053e-01,  6.12187768e-03, -8.23519458e-01,
          3.23857154e+00, -4.87333909e-01,  3.208054

In [14]:
a= np.array(a)
print(a.shape)

(140, 40, 10)


In [15]:
label = []

file_numpy = np.load('/home/libedev/mute/mute-hero/download/dataset/new_train_label.npy')

label.append(file_numpy)

In [17]:
label = np.array(label)

In [18]:
label.shape

(1, 400)

In [ ]:
label = label.reshape(400,label)

In [21]:
train_label = []
file_numpy=np.load('/home/libedev/mute/mute-hero/download/dataset/new_train_label.npy')
train_label = train_label.append(file_numpy)

In [26]:
file_numpy

array([7, 7, 4, 4, 0, 6, 7, 5, 1, 2, 7, 6, 6, 2, 5, 3, 0, 7, 7, 4, 5, 3,
       3, 1, 0, 1, 3, 7, 3, 5, 6, 0, 3, 0, 1, 3, 0, 7, 0, 2, 2, 0, 3, 4,
       4, 4, 4, 7, 3, 4, 2, 7, 0, 7, 0, 0, 5, 2, 3, 5, 7, 5, 1, 7, 3, 6,
       4, 5, 2, 0, 4, 3, 1, 4, 6, 1, 7, 1, 2, 2, 2, 1, 3, 7, 7, 6, 0, 7,
       0, 3, 6, 3, 1, 0, 5, 4, 4, 3, 5, 3, 1, 7, 5, 2, 0, 6, 0, 7, 4, 4,
       1, 1, 6, 3, 0, 1, 1, 3, 5, 7, 7, 5, 0, 5, 7, 2, 6, 4, 3, 4, 3, 1,
       7, 2, 4, 4, 7, 1, 0, 4, 5, 7, 3, 4, 0, 1, 7, 3, 0, 7, 6, 4, 3, 6,
       2, 2, 2, 6, 2, 0, 7, 7, 6, 6, 1, 5, 4, 5, 5, 4, 3, 4, 4, 4, 6, 7,
       5, 3, 3, 6, 5, 6, 2, 1, 7, 3, 2, 0, 0, 1, 7, 0, 0, 0, 6, 6, 1, 6,
       1, 2, 1, 6, 5, 7, 2, 5, 3, 3, 3, 1, 4, 0, 2, 3, 7, 7, 5, 3, 1, 7,
       1, 0, 1, 7, 6, 0, 4, 2, 2, 0, 5, 0, 7, 1, 4, 6, 7, 3, 5, 6, 0, 0,
       4, 5, 4, 3, 2, 6, 0, 2, 5, 3, 4, 4, 2, 2, 3, 5, 2, 6, 1, 4, 1, 6,
       3, 7, 2, 5, 2, 6, 7, 5, 6, 4, 2, 5, 6, 2, 2, 3, 5, 2, 4, 2, 5, 6,
       4, 0, 5, 1, 2, 3, 5, 4, 5, 0, 1, 7, 1, 4, 4,

In [27]:
file_numpy[0]

7

In [209]:
root = '/home/libedev/mute/mute-hero/download/dataset/new_train/'
        
# option --> 전처리 폴더명
option = 'spectrum_Mel_PCA'+'/'

        
        
#add = self.root + self.option
        
all_files = os.path.join(root,option)
        
data=[os.path.join(dirpath,f)for dirpath, dirnames, filenames in os.walk(all_files) for f in filenames] 
        
        

train_data =[]
train_label =[]
            
#file_numpy=np.load('/home/libedev/mute/mute-hero/download/dataset/'+str(option2)+'.npy')
#self.train_label = self.train_label.append(file_numpy)
            
            
for f in data:
                
    train_data.append(np.load(f))

In [210]:
train_data = np.array(train_data)
train_data = train_data.reshape((train_data.shape[0],1,train_data.shape[1],train_data.shape[2]))
#train_data = train_data.transpose((0,2,3,1))       

In [ ]:
inputs_tensors = torch.stack([torch.Tensor(i) for i in tra])

In [211]:
train_data =  [train_data]


In [212]:
train_data = np.array([train_data])
print(train_data.shape)
train_data = train_data.transpose((1,0,2,3))

(1, 1, 400, 1, 40, 10)


ValueError: axes don't match array

In [187]:
print(train_data.shape)


(400, 1, 40, 10)


In [190]:
train_data = torch.from_numpy(train_data) 

In [192]:
print(train_data[0].shape)
print(train_data.shape)

torch.Size([1, 40, 10])
torch.Size([400, 1, 40, 10])


In [62]:
x = torch.Tensor([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]])
print(x.shape)

torch.Size([1, 1, 3, 4])


In [110]:
train_label=[]

In [221]:
file_numpy=np.load('/home/libedev/mute/mute-hero/download/dataset/new_train_label.npy')
file_numpy


array([7, 7, 4, 4, 0, 6, 7, 5, 1, 2, 7, 6, 6, 2, 5, 3, 0, 7, 7, 4, 5, 3,
       3, 1, 0, 1, 3, 7, 3, 5, 6, 0, 3, 0, 1, 3, 0, 7, 0, 2, 2, 0, 3, 4,
       4, 4, 4, 7, 3, 4, 2, 7, 0, 7, 0, 0, 5, 2, 3, 5, 7, 5, 1, 7, 3, 6,
       4, 5, 2, 0, 4, 3, 1, 4, 6, 1, 7, 1, 2, 2, 2, 1, 3, 7, 7, 6, 0, 7,
       0, 3, 6, 3, 1, 0, 5, 4, 4, 3, 5, 3, 1, 7, 5, 2, 0, 6, 0, 7, 4, 4,
       1, 1, 6, 3, 0, 1, 1, 3, 5, 7, 7, 5, 0, 5, 7, 2, 6, 4, 3, 4, 3, 1,
       7, 2, 4, 4, 7, 1, 0, 4, 5, 7, 3, 4, 0, 1, 7, 3, 0, 7, 6, 4, 3, 6,
       2, 2, 2, 6, 2, 0, 7, 7, 6, 6, 1, 5, 4, 5, 5, 4, 3, 4, 4, 4, 6, 7,
       5, 3, 3, 6, 5, 6, 2, 1, 7, 3, 2, 0, 0, 1, 7, 0, 0, 0, 6, 6, 1, 6,
       1, 2, 1, 6, 5, 7, 2, 5, 3, 3, 3, 1, 4, 0, 2, 3, 7, 7, 5, 3, 1, 7,
       1, 0, 1, 7, 6, 0, 4, 2, 2, 0, 5, 0, 7, 1, 4, 6, 7, 3, 5, 6, 0, 0,
       4, 5, 4, 3, 2, 6, 0, 2, 5, 3, 4, 4, 2, 2, 3, 5, 2, 6, 1, 4, 1, 6,
       3, 7, 2, 5, 2, 6, 7, 5, 6, 4, 2, 5, 6, 2, 2, 3, 5, 2, 4, 2, 5, 6,
       4, 0, 5, 1, 2, 3, 5, 4, 5, 0, 1, 7, 1, 4, 4,

In [113]:
train_label
train_label = np.array(train_label)
print()

In [222]:
train_label2 = torch.as_tensor(np.array(file_numpy))
print(train_label2.shape)

print("\n\n")



#train_label2.view(1,400).squeeze()
print(train_label2)

torch.Size([400])



tensor([7, 7, 4, 4, 0, 6, 7, 5, 1, 2, 7, 6, 6, 2, 5, 3, 0, 7, 7, 4, 5, 3, 3, 1,
        0, 1, 3, 7, 3, 5, 6, 0, 3, 0, 1, 3, 0, 7, 0, 2, 2, 0, 3, 4, 4, 4, 4, 7,
        3, 4, 2, 7, 0, 7, 0, 0, 5, 2, 3, 5, 7, 5, 1, 7, 3, 6, 4, 5, 2, 0, 4, 3,
        1, 4, 6, 1, 7, 1, 2, 2, 2, 1, 3, 7, 7, 6, 0, 7, 0, 3, 6, 3, 1, 0, 5, 4,
        4, 3, 5, 3, 1, 7, 5, 2, 0, 6, 0, 7, 4, 4, 1, 1, 6, 3, 0, 1, 1, 3, 5, 7,
        7, 5, 0, 5, 7, 2, 6, 4, 3, 4, 3, 1, 7, 2, 4, 4, 7, 1, 0, 4, 5, 7, 3, 4,
        0, 1, 7, 3, 0, 7, 6, 4, 3, 6, 2, 2, 2, 6, 2, 0, 7, 7, 6, 6, 1, 5, 4, 5,
        5, 4, 3, 4, 4, 4, 6, 7, 5, 3, 3, 6, 5, 6, 2, 1, 7, 3, 2, 0, 0, 1, 7, 0,
        0, 0, 6, 6, 1, 6, 1, 2, 1, 6, 5, 7, 2, 5, 3, 3, 3, 1, 4, 0, 2, 3, 7, 7,
        5, 3, 1, 7, 1, 0, 1, 7, 6, 0, 4, 2, 2, 0, 5, 0, 7, 1, 4, 6, 7, 3, 5, 6,
        0, 0, 4, 5, 4, 3, 2, 6, 0, 2, 5, 3, 4, 4, 2, 2, 3, 5, 2, 6, 1, 4, 1, 6,
        3, 7, 2, 5, 2, 6, 7, 5, 6, 4, 2, 5, 6, 2, 2, 3, 5, 2, 4, 2, 5, 6, 4, 0,
        5, 1, 2, 3,

In [223]:
print(train_label2[99].shape)
print(train_label2.shape)

torch.Size([])
torch.Size([400])


In [224]:
print(len(train_label2))

400


In [89]:
train_label = train_label.append(file_numpy)